# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/master/.golangci.yaml as a reference.
run:
  timeout: 5m

output:
  format: tab

# See https://golangci-lint.run/usage/linters/ for description of linters
linters:
  disable-all: true
  enable:
    # default linters
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # non default linters
    - revive
    - goerr113
    - goimports
    - misspell
    - asciicheck
    - bidichk
    - makezero

issues:
  exclude-rules:
      # Disallows any kind of `fmt.Errorf("%s is too high", bar)`, too opinionated.
    - linters: [goerr113]
      text: "do not define dynamic errors, use wrapped static errors instead"
      # Most exported consts are self-descriptive.
    - linters: [revive]
      text: "exported const"
    - linters: [revive]
      text: "var-naming"
