# deny connections to 34.116.205.187:443, c2 server
apiVersion: "cilium.io/runtime/v1"
kind: CiliumRuntimeSecurityPolicy
metadata:
  name: "deny-c2-connection"
  namespace: "default"
Spec:
  policyMode: Block
  podSelector:
	matchLabels:
  process:
  	binary: "*"
  network:
    ip: "34.116.205.187"
    port: "443"