apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "url"
  annotations:
    author: "Kevin Sheldrake <kevin.sheldrake@isovalent.com>"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/etc/passwd"
      matchActions:
      - action: GetUrl
        argUrl: http://ebpf.io
