name: vmtests-macos
on:
  pull_request:
   paths-ignore:
   - "**.md"
  push:
    branches:
      - main
jobs:
  build:
    name: Build tetragon
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.ref }}-vmtest-build
      cancel-in-progress: true
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.3'

    - name: Install docker
      uses: docker-practice/actions-setup-docker@master

    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        path: go/src/github.com/cilium/tetragon/

    - name: Install build dependencies
      run: |
        sudo apt install libelf-dev netcat-traditional libcap-dev gcc
        echo `which clang`
        echo `which llc`
        echo `clang --version`
    - name: Build
      env:
        GOPATH: /home/runner/work/tetragon/tetragon/go
      run: |
        cd go/src/github.com/cilium/tetragon/
        make tetragon-bpf tester-progs test-compile
        make -C tests/vmtests

      # NB: even though we have a single grop, we still need to "split" tests to apply our blacklist
    - name: Split tests
      run: |
        cd go/src/github.com/cilium/tetragon/
        go run ./tools/split-tetragon-gotests -ci-run 5

    - name: Install dependencies for building images
      run: |
        sudo apt-get -qy install mmdebstrap libguestfs-tools qemu-utils

    - name: Make kernel accessible
      run: |
        sudo chmod go+rX -R /boot/

    - name: Download rootfs and kernel images
      run: |
        cd go/src/github.com/cilium/tetragon/
        tests/vmtests/fetch-data.sh -b -k 5.10 -k 5.4 -k 4.19

    - name: Build rootfs image
      run: |
        cd go/src/github.com/cilium/tetragon/
        #  NB: we copy the btf file for 4.19
        ./tests/vmtests/tetragon-vmtests-run  \
                   --base ./tests/vmtests/test-data/images/base.qcow2 \
                   --just-build-image \
                   --testsfile ./tests/vmtests/my-test-group \
                   --btf-file tests/vmtests/test-data/kernels/4.19/boot/btf-*
        zstd --rm --compress ./tests/vmtests/test-data/images/tetragon.qcow2
        rm ./tests/vmtests/test-data/images/base*

    - name: Create tar file
      run: |
        cd go/src/github.com/cilium/
        tar cz --exclude='tetragon/.git' -f /tmp/tetragon.tar ./tetragon

    - name: Upload build tar file
      uses: actions/upload-artifact@v3
      with:
         name: tetragon-build
         path: /tmp/tetragon.tar
         retention-days: 1
  test:
    strategy:
        fail-fast: false
        matrix:
           kernel:
             - '5.10'
             - '5.4'
             - '4.19'
           group:
             - 0
             - 1
             - 2
             - 3
             - 4
    concurrency:
      group: ${{ github.ref }}-vmtest-${{ matrix.kernel }}-${{ matrix.group }}
      cancel-in-progress: true
    needs: build
    name: Test kernel ${{ matrix.kernel }} / test group ${{ matrix.group }}
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
    - name: Install docker
      run: |
        brew install docker

    - name: Install VM test dependencies
      run: |
        brew install qemu

    - name: Download build data
      uses: actions/download-artifact@v3
      with:
         name: tetragon-build

    - name: Extract build data
      # NB: currently, due to how tests work, we need to extract to the same path.
      run: |
        mkdir -p go/src/github.com/cilium/
        tar xf tetragon.tar -C go/src/github.com/cilium
        zstd --decompress --rm go/src/github.com/cilium/tetragon/tests/vmtests/test-data/images/tetragon.qcow2.zst

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.3'

    - name: Build vmtest runner
      run: |
        cd go/src/github.com/cilium/tetragon
        make -C tests/vmtests tetragon-vmtests-run

    - name: test kernel ${{ matrix.kernel }}
      if: ${{ matrix.kernel  != '4.19' }}
      run: |
        cd go/src/github.com/cilium/tetragon
        # configured when building the image
        cp ./tests/vmtests/test-group-${{ matrix.group }} ./tests/vmtests/my-test-group
        ./tests/vmtests/tetragon-vmtests-run \
                --kernel tests/vmtests/test-data/kernels/${{ matrix.kernel }}/boot/vmlinuz* \
                --base tests/vmtests/test-data/images/base.qcow2 \
                --dont-rebuild-image \
                --qemu-enable-hvf \

    - name: test kernel ${{ matrix.kernel }} with btf file
      if: ${{ matrix.kernel  == '4.19' }}
      run: |
        cd go/src/github.com/cilium/tetragon
        # configured when building the image
        cp ./tests/vmtests/test-group-${{ matrix.group }} ./tests/vmtests/my-test-group
        ./tests/vmtests/tetragon-vmtests-run \
                --kernel tests/vmtests/test-data/kernels/${{ matrix.kernel }}/boot/vmlinuz* \
                --base tests/vmtests/test-data/images/base.qcow2 \
                --btf-file tests/vmtests/test-data/kernels/${{ matrix.kernel }}/boot/btf-* \
                --dont-rebuild-image \
                --qemu-enable-hvf \

    - name: Upload test results on failure or cancelation
      if: failure() || cancelled()
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
      with:
        name: tetragon-vmtests-${{ matrix.kernel }}-${{ matrix.group }}-results
        path: |
          go/src/github.com/cilium/tetragon/tests/vmtests/vmtests-results
          /tmp/tetragon.gotest.*
        retention-days: 5

  post-success:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
    - name: Create truncated build file
      run: |
        touch /tmp/tetragon.tar
    - name: Upload truncated file
      uses: actions/upload-artifact@v3
      with:
         name: tetragon-build
         path: /tmp/tetragon.tar
         retention-days: 1
  post-failure:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
    - name: print info
      run: |
        echo "You can find the artifact URLs using:"
        echo "curl -s  https://api.github.com/repos/cilium/tetragon/actions/runs/$GITHUB_RUN_ID/artifacts | jq '.artifacts | .[] | .name + \": \" + .url'"
